[#-- ISO 3166 codes https://en.wikipedia.org/wiki/ISO_3166 --]
[#assign countryCodes = {
    "Afghanistan" : "af",
    "Albanië" : "al",
    "Algerije" : "dz",
    "Amerikaans-Samoa" : "as",
    "Amerikaanse Maagdeneilanden" : "vi",
    "Andorra" : "ad",
    "Angola" : "ao",
    "Anguilla" : "ai",
    "Antarctica" : "aq",
    "Antigua en Barbuda" : "ag",
    "Argentinië" : "ar",
    "Armenië" : "am",
    "Aruba" : "aw",
    "Australië" : "au",
    "Azerbeidzjan" : "az",
    "Åland" : "ax",
    "Bahama's" : "bs",
    "Bahrein" : "bh",
    "Bangladesh" : "bd",
    "Barbados" : "bb",
    "Belarus" : "by",
    "België" : "be",
    "Belize" : "bz",
    "Bermuda" : "bm",
    "Benin" : "bj",
    "Bhutan" : "bt",
    "Bolivia" : "bo",
    "Bonaire, Sint Eustatius en Saba" : "bq",
    "Bosnië en Herzegovina" : "ba",
    "Botswana" : "bw",
    "Bouvet" : "bv",
    "Brazilië" : "br",
    "Brits Territorium in de Indische Oceaan" : "io",
    "Britse Maagdeneilanden" : "vg",
    "Brunei" : "bn",
    "Bulgarije" : "bg",
    "Burkina Faso" : "bf",
    "Burundi" : "bi",
    "Cambodja" : "kh",
    "Canada" : "ca",
    "Centraal-Afrikaanse Republiek" : "cf",
    "Chili" : "cl",
    "China" : "cn",
    "Christmaseiland" : "cx",
    "Cocoseilanden" : "cc",
    "Colombia" : "co",
    "Comoren" : "km",
    "Congo-Brazzaville" : "cg",
    "Congo-Kinshasa" : "cd",
    "Cookeilanden" : "ck",
    "Costa Rica" : "cr",
    "Cuba" : "cu",
    "Curaçao" : "cw",
    "Cyprus" : "cy",
    "Denemarken" : "dk",
    "Djibouti" : "dj",
    "Dominica" : "dm",
    "Dominicaanse Republiek" : "do",
    "Duitsland" : "de",
    "Ecuador" : "ec",
    "Egypte" : "eg",
    "El Salvador" : "sv",
    "Engeland" : "gb-eng",
    "Equatoriaal-Guinea" : "gq",
    "Eritrea" : "er",
    "Estland" : "ee",
    "Ethiopië" : "et",
    "Europa" : "eu",
    "Faeröer" : "fo",
    "Falklandeilanden" : "fk",
    "Fiji" : "fj",
    "Filipijnen" : "ph",
    "Finland" : "fi",
    "Frankrijk" : "fr",
    "Frans-Guyana" : "gf",
    "Frans-Polynesië" : "pf",
    "Franse Zuidelijke en Antarctische Gebieden" : "tf",
    "Gabon" : "ga",
    "Gambia" : "gm",
    "Georgië" : "ge",
    "Ghana" : "gh",
    "Gibraltar" : "gi",
    "Grenada" : "gd",
    "Griekenland" : "gr",
    "Groenland" : "gl",
    "Guadeloupe" : "gp",
    "Guam" : "gu",
    "Guatemala" : "gt",
    "Guernsey" : "gg",
    "Guinee" : "gn",
    "Guinee-Bissau" : "gw",
    "Guyana" : "gy",
    "Haïti" : "ht",
    "Heard en McDonaldeilanden" : "hm",
    "Honduras" : "hn",
    "Hongarije" : "hu",
    "Hongkong" : "hk",
    "Ierland" : "ie",
    "IJsland" : "is",
    "India" : "in",
    "Indonesië" : "id",
    "Irak" : "iq",
    "Iran" : "ir",
    "Israël" : "il",
    "Italië" : "it",
    "Ivoorkust" : "ci",
    "Jamaica" : "jm",
    "Japan" : "jp",
    "Jemen" : "ye",
    "Jersey" : "je",
    "Jordanië" : "jo",
    "Kaaimaneilanden" : "ky",
    "Kaapverdië" : "cv",
    "Kameroen" : "cm",
    "Kazachstan" : "kz",
    "Kenia" : "ke",
    "Kirgizië" : "kg",
    "Kiribati" : "ki",
    "kleine afgelegen eilanden van de Verenigde Staten" : "um",
    "Koeweit" : "kw",
    "Kroatië" : "hr",
    "Laos" : "la",
    "Lesotho" : "ls",
    "Letland" : "lv",
    "Libanon" : "lb",
    "Liberia" : "lr",
    "Libië" : "ly",
    "Liechtenstein" : "li",
    "Litouwen" : "lt",
    "Luxemburg" : "lu",
    "Macau" : "mo",
    "Macedonië" : "mk",
    "Madagaskar" : "mg",
    "Malawi" : "mw",
    "Maldiven" : "mv",
    "Maleisië" : "my",
    "Mali" : "ml",
    "Malta" : "mt",
    "Man" : "im",
    "Marokko" : "ma",
    "Marshalleilanden" : "mh",
    "Martinique" : "mq",
    "Mauritanië" : "mr",
    "Mauritius" : "mu",
    "Mayotte" : "yt",
    "Mexico" : "mx",
    "Micronesia" : "fm",
    "Moldavië" : "md",
    "Monaco" : "mc",
    "Mongolië" : "mn",
    "Montenegro" : "me",
    "Montserrat" : "ms",
    "Mozambique" : "mz",
    "Myanmar" : "mm",
    "Namibië" : "na",
    "Nauru" : "nr",
    "Nederland" : "nl",
    "Nepal" : "np",
    "Nicaragua" : "ni",
    "Nieuw-Caledonië" : "nc",
    "Nieuw-Zeeland" : "nz",
    "Niger" : "ne",
    "Nigeria" : "ng",
    "Niue" : "nu",
    "Noord-Ierland" : "gb-nir",
    "Noord-Korea" : "kp",
    "Noordelijke Marianen" : "mp",
    "Noorwegen" : "no",
    "Norfolk" : "nf",
    "Oeganda" : "ug",
    "Oekraïne" : "ua",
    "Oezbekistan" : "uz",
    "Oman" : "om",
    "Oost-Timor" : "tl",
    "Oostenrijk" : "at",
    "Pakistan" : "pk",
    "Palau" : "pw",
    "Palestijnse Gebieden" : "ps",
    "Panama" : "pa",
    "Papoea-Nieuw-Guinea" : "pg",
    "Paraguay" : "py",
    "Peru" : "pe",
    "Pitcairneilanden" : "pn",
    "Polen" : "pl",
    "Portugal" : "pt",
    "Puerto Rico" : "pr",
    "Qatar" : "qa",
    "Réunion" : "re",
    "Roemenië" : "ro",
    "Rusland" : "ru",
    "Rwanda" : "rw",
    "Saint Kitts en Nevis" : "kn",
    "Saint Lucia" : "lc",
    "Saint Vincent en de Grenadines" : "vc",
    "Saint-Barthélemy" : "bl",
    "Saint-Martin" : "mf",
    "Saint-Pierre en Miquelon" : "pm",
    "Salomonseilanden" : "sb",
    "Samoa" : "ws",
    "San Marino" : "sm",
    "Sao Tomé en Principe" : "st",
    "Saoedi-Arabië" : "sa",
    "Schotland" : "gb-sct",
    "Senegal" : "sn",
    "Servië" : "rs",
    "Seychellen" : "sc",
    "Sierra Leone" : "sl",
    "Singapore" : "sg",
    "Sint Maarten" : "sx",
    "Sint-Helena, Ascension en Tristan da Cunha" : "sh",
    "Slovenië" : "si",
    "Slowakije" : "sk",
    "Soedan" : "sd",
    "Somalië" : "so",
    "Spanje" : "es",
    "Spitsbergen en Jan Mayen" : "sj",
    "Sri Lanka" : "lk",
    "Suriname" : "sr",
    "Swaziland" : "sz",
    "Syrië" : "sy",
    "Tadzjikistan" : "tj",
    "Taiwan" : "tw",
    "Tanzania" : "tz",
    "Thailand" : "th",
    "Togo" : "tg",
    "Tonga" : "to",
    "Tokelau" : "tk",
    "Trinidad en Tobago" : "tt",
    "Tsjaad" : "td",
    "Tsjechië" : "cz",
    "Tunesië" : "tn",
    "Turkije" : "tr",
    "Turkmenistan" : "tm",
    "Turks- en Caicoseilanden" : "tc",
    "Tuvalu" : "tv",
    "Uruguay" : "uy",
    "Vanuatu" : "vu",
    "Vaticaanstad" : "va",
    "Venezuela" : "ve",
    "Verenigd Koninkrijk" : "gb",
    "Verenigde Arabische Emiraten" : "ae",
    "Verenigde Naties" : "un",
    "Verenigde Staten" : "us",
    "Vietnam" : "vn",
    "Wales" : "gb-wls",
    "Wallis en Futuna" : "wf",
    "Westelijke Sahara" : "eh",
    "Wit-Rusland" : "by",
    "Zambia" : "zm",
    "Zimbabwe" : "zw",
    "Zuid-Afrika" : "za",
    "Zuid-Georgië en de Zuidelijke Sandwicheilanden" : "gs",
    "Zuid-Korea" : "kr",
    "Zuid-Soedan" : "ss",
    "Zweden" : "se",
    "Zwitserland" : "ch"
}]