[#assign countryCodes = {
    "fr" : "Frankrijk",
    "gb-eng" : "Engeland",
    "cz" : "Tjechië",
    "is" : "IJsland",
    "at" : "Oostenrijk",
    "gb-nir" : "Noord-Ierland",
    "pt" : "Portugal",
    "es" : "Spanje",
    "ch" : "Zwitserland",
    "it" : "Italië",
    "be" : "België",
    "gb-wls" : "Wales",
    "ro" : "Roemenië",
    "al" : "Albanië",
    "de" : "Duitsland",
    "pl" : "Polen",
    "ru" : "Rusland",
    "sk" : "Slowakije",
    "hr" : "Kroatië",
    "tr" : "Turkije",
    "hu" : "Hongarije",
    "nl" : "Ierland",
    "se" : "Zweden",
    "ua" : "Oekraine"
}]