[#-- ISO 3166 codes https://en.wikipedia.org/wiki/ISO_3166 --]
[#assign countryCodes = {
    "Albanië" : "al",
    "België" : "be",
    "Duitsland" : "de",
    "Engeland" : "gb-eng",
    "Frankrijk" : "fr",
    "Hongarije" : "hu",
    "Ierland" : "ie",
    "IJsland" : "is",
    "Italië" : "it",
    "Kroatië" : "hr",
    "Noord-Ierland" : "gb-nir",
    "Oekraïne" : "ua",
    "Oostenrijk" : "at",
    "Polen" : "pl",
    "Portugal" : "pt",
    "Roemenië" : "ro",
    "Rusland" : "ru",
    "Slowakije" : "sk",
    "Spanje" : "es",
    "Tjechië" : "cz",
    "Turkije" : "tr",
    "Wales" : "gb-wls",
    "Zweden" : "se",
    "Zwitserland" : "ch"
}]